<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[12]=array(0,-17,1,'6KGM5Lia5oql5ZGK');
$cfg_Cs[16]=array(13,-17,1,'54Wk54Kt');
$cfg_Cs[13]=array(12,-17,0,'6IO95rqQ55S15Yqb');
$cfg_Cs[14]=array(13,-17,1,'5paw6IO95rqQ');
$cfg_Cs[15]=array(13,-17,1,'5aSq6Ziz6IO9');
$cfg_Cs[17]=array(13,-17,1,'55+z5rK55aSp54S25rCU');
$cfg_Cs[18]=array(13,-17,1,'55S15Yqb');
$cfg_Cs[20]=array(13,-17,1,'5Yy65Z+f6IO95rqQ');
?>