<li>
							<a title="[field:fulltitle/]" href="[field:arcurl /]">[field:title /]</a>
							<p class="intro"> </p>
							<div class="ptxt">
                            <p class="pic">
                                <a href="[field:arcurl /]" target="_blank">
                                    <img src="http://img3.qianzhan123.com/report/cover/a3/a38f5aabdd65437a.gif" alt="[field:fulltitle/]" width="110" height="110"></a>
                                 </p>                            
                            <p class="txt">[field:descriptions function='cn_substr(@me,300)' /]...［<a href="[field:arcurl /]" target="_blank" class="fontblue">详细</a>］</p>
                        </div>
						</li>