<li>
							<a title="[field:fulltitle/]" href="[field:arcurl /]">[field:title /]</a>
							<div class="ptxt">
                            <p class="pic">
                                <a href="[field:arcurl /]" target="_blank">
                                    <img src="[field:imglink/]" alt="[field:fulltitle/]" width="110" height="110"></a>
                                 </p>                            
                            <p class="txt">[field:descriptions function='cn_substr(@me,380)' /]...［<a href="[field:arcurl /]" target="_blank" class="fontblue">详细</a>］</p>
                        </div>
						</li>