<li>
							<a title="[field:fulltitle/]" href="[field:arcurl /]">[field:title /]</a>
							<p class="intro"> </p>
							<div class="ptxt">
                            <p class="pic">
                                
                                <a href="http://bg.qianzhan.com/report/detail/a38f5aabdd65437a.html" target="_blank">
                                    <img src="http://img3.qianzhan123.com/report/cover/a3/a38f5aabdd65437a.gif" alt="2017-2022年四川省柴油行业应用领域市场需求与投资预测分析报告" width="110" height="110"></a>
                                 </p>                            
                            <p class="txt">[field:descriptions/]...［<a href="[field:fulltitle/]" target="_blank" class="fontblue">详细</a>］</p>
                        </div>
						</li>